version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=sqlite:///app.db

  db:
    image: sqlite:latest
    volumes:
      - ./app.db:/app.db
